### ISSUE TITLE
Way to clear/flush queue

### ISSUE THREAD

**Issue by mariah-smith25** [cameron314/readerwriterqueue#104]
Hello,
I'm using the readerwriterqueue to do some Android NDK & ffmpeg encoding. Every once in a while the encoding thread will fail and I need to be able to flush the readerwriterqueue at this point. Is this possible with the current API? If not, is it possible to add this?

**Comment by cameron314** [comment]
This cannot be done in a safe way under contention. The reader will need to empty the queue one element at a time.

Alternatively, if the queue is not under contention, it can be move-assigned an empty temporary object, effectively clearing it.
