### ISSUE TITLE
Include header files in cmake target

### ISSUE THREAD

**Issue by Wedrew** [cameron314/readerwriterqueue#105]
Hi,

Would it be possible to update the cmake script to have the cmake target readerwriterqueue include the header files associated with it? add_subdirectory() and FetchContent_Declare() are widely used to bring in third party libraries to cmake projects and without the information of the headers, the use of those functions will be useless.

Simply adding the line:
target_include_directories(readerwriterqueue INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})

after:
add_library(${PROJECT_NAME} INTERFACE)

would alleviate this problem.

Thanks!

**Comment by cameron314** [comment]
Certainly. I don't use cmake so I'll take your word for it :-)
