### ISSUE TITLE
warning C4316

### ISSUE THREAD

**Issue by TheSwAda** [cameron314/readerwriterqueue#109]
Development OS: Windows 10 64 bit
IDE: Visual Studio 2013 Professional
 Language: C++

The Problem:
I get the following warning when compiling project through the IDE:
warning C4316: ... : object allocated on the heap may not be aligned 64

The Code:
struct A
{
ReaderWriterQueue<int> data;
int a; 
}
A *a= new A;

**Comment by cameron314** [comment]
This is normal and can be safely ignored. See issue #107. Sorry for the inconvenience.
