### ISSUE TITLE
How could double-check really happen in funciont try_dequeue()

### ISSUE THREAD

**Issue by angon823** [cameron314/readerwriterqueue#117]
hello, cameron314,

When I was reading the readerwriterqueue.h, I was confused for hours by the double-check in the [try_enqueue function](https://github.com/cameron314/readerwriterqueue/blob/09732844aff873e8ec489e9005c775b6b1c58fa2/readerwriterqueue.h#L335).  Why is that necessary？
Especially, In [here](https://github.com/cameron314/readerwriterqueue/blob/09732844aff873e8ec489e9005c775b6b1c58fa2/readerwriterqueue.h#L301)  your explanation is **"Seems unlikely, but was consistently reproducible in practiced"**

Fortunately, I finally found an example that have to double-check:

when the queue has no data(means frontBlock==tailBlock, and the block is also emty),
[line312](https://github.com/cameron314/readerwriterqueue/blob/09732844aff873e8ec489e9005c775b6b1c58fa2/readerwriterqueue.h#L312)'  if statement will returns false, so it enters the judgment of the else if. Here comes the point: after the end of the if, before the start of the else if, the producer fills up the front block *and moves on*, so `else if (frontBlock_ != tailBlock.load())  ` return true, and  at this time frontBlock already has data. so it have to check frontBlock again in else if.

Is my thinking correct? If it is correct, might you can update the comments in the code to make it easier for later generations to understand.

Thank you for your code and meticulous and reliable testing!

**Comment by cameron314** [comment]
Yes exactly. This is what the existing comments attempt to explain :-)

After determining that the head block != the tail block, the code must check if the head .
