### ISSUE TITLE
example with unique_ptr or shared_ptr

### ISSUE THREAD

**Issue by mipac** [cameron314/readerwriterqueue#118]
Hi,
Can you give an example with unique_ptr type?

**Comment by cameron314** [comment]
It's pretty much as you might expect:

    moodycamel::ReaderWriterQueue<std::unique_ptr<int>> q;
    auto p = std::make_unique<int>(123);

    q.enqueue(std::move(p));
    assert(!p);

    q.try_dequeue(p);
    assert(*p == 123);
