### ISSUE TITLE
blocking dequeue until enqueue

### ISSUE THREAD

**Issue by vlovich** [cameron314/readerwriterqueue#12]
Is there an efficient way of implementing a blocking dequeue?  Am I thinking about it wrong?  I don't want my consumer thread spinning if there's no data.

**Comment by mintyc** [comment]
Definitely something desirable for the consumer to block. I've implemented with a condition_var in a wrapper but I can't help feeling I've just slugged any performance gain from using your queue :)

For your cross platform semaphore you could check out
http://preshing.com/20150316/semaphores-are-surprisingly-versatile/
and in particular his cross platform semaphore implementation https://github.com/preshing/cpp11-on-multicore

**Comment by cameron314** [comment]
@mintyc: Yep, I'm already working on a blocking version that uses Jeff's portable semaphore (and his lightweight spinning wrapper, which is pretty much what I was envisioning writing myself, except that Jeff beat me to it, haha).

Coming soon to a repository near you.

**Comment by cameron314** [comment]
Done! Thanks to all for your help and patience.
