### ISSUE TITLE
Do Producer and Consumer sides need to be the same thread, or serialized access of those sides is enough?

### ISSUE THREAD

**Issue by ddevienne** [cameron314/readerwriterqueue#121]
Hi. I'd like to use this _single-threaded_ queue (in blocking variant) in a different context, where I do not control the thread that the Producer side will run on, but still guarantee that it will be _serialized_. That's because this is in a Boost.ASIO context and reactive-programming, and thus ASIO may choose any available thread from its pool to call me, at which point I can enqueue to your queue (for later processing on dequeue by more higher-level downstream code, not aware of the Boost.ASIO layer).

So my question is whether the various enqueue calls called from different threads, but still serialized, is a deal-breaker for usage of your queue? And I guess if I should switch instead to your MPSC ConcurrentQueue? Or even resort back to lock-based programming on my own (which it more error prone from my end).

In either case, perhaps the doc would benefit from clarification regarding the above. Thanks, --DD

PS: In this particular case, the Consumer side is a single-thread for sure. But ideally, I'd like to know the single-thread-vs-serialized answers for either or both _sides_.

**Comment by cameron314** [comment]
That's fine, you can use the (Blocking)ReaderWriterQueue. It doesn't depend on the actual thread context (no thread-local storage, etc.) so safely serialized accesses are not a problem. 

For the ConcurrentQueue, there *are* thread-local constructs when enqueueing implicitly, but using a single explicit producer token with serialized accesses would be fine there as well.

**Comment by ddevienne** [comment]
Thanks for the quick feedback! Cheers, --DD
