### ISSUE TITLE
What does this assert mean?

### ISSUE THREAD

**Issue by mpuskas** [cameron314/readerwriterqueue#128]
Hello, a coworker noticed an assert that we're having trouble reproducing, and I'm looking for more information on it. We're using a BlockingReaderWriterQueue in embedded linux on an Arm v8-A platform.

```
source/lib/readerwriterqueue/atomicops.h:658: void moodycamel::spsc_sema::LightweightSemaphore::signal(moodycamel::spsc_sema::LightweightSemaphore::ssize_t): Assertion `oldCount >= -1' failed.
```

We're on an older SHA, it looks like it matches the current [line 669](https://github.com/cameron314/readerwriterqueue/blob/1f3c8e4213115484bcc6d49255b65526ed38cf5b/atomicops.h#L669)

Any thoughts? Thanks!

**Comment by cameron314** [comment]
This could occur if there's more than one thread consuming from the queue.

Also, please update to the latest master, there were some fixes around signals while blocking on the semaphore at one point.

**Comment by mpuskas** [comment]
Good to know, thanks for the quick reply! We'll update to latest master and verify that we don't have multiple consumers.

**Comment by poor1017** [comment]
@cameron314 Hi, this issue is not fixed with the latest master. Can I just remove this assert directly? Thanks!

**Comment by cameron314** [comment]
No, if this assert is firing it indicates a bug somewhere, either in the queue or in the calling code. Can you share an example that reproduces?

**Comment by poor1017** [comment]
Here is the example source code:
``` c++
#include <unistd.h>

#include <iostream>
#include <thread>

#include "readerwriterqueue.h"

typedef moodycamel::BlockingReaderWriterQueue<int> InputQueue;
auto input_queue = std::make_shared<InputQueue>();

void
startWorkLoop()
{
    while (true) {
        int input = 0;
        input_queue->wait_dequeue(input);
    }
}

void
startClientLoop()
{
    while (true) {
        sleep(2);
        std::cout << "enqueue ..." << std::endl;
        int input = 1;
        input_queue->enqueue(input);
    }
}

int
main(int argc, char **argv)
{
    std::shared_ptr<std::thread> thread1 = std::make_shared<std::thread>(&startWorkLoop);
    std::shared_ptr<std::thread> thread2 = std::make_shared<std::thread>(&startWorkLoop);

    std::shared_ptr<std::thread> client = std::make_shared<std::thread>(&startClientLoop);

    thread1->join();
    thread2->join();
    client->join();

    return 0;
}
```

Here is the CMakeLists.txt
``` cmake
cmake_minimum_required(VERSION 3.10.1)
project(verify)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++17 -pthread -W")
set(CMAKE_BUILD_TYPE "Debug")

add_executable(main main.cc)
```

OS: Ubuntu 20.04

**Comment by cameron314** [comment]
You have one producer thread but two consumer threads. This is an SPSC queue (supports single consumer only).

**Comment by poor1017** [comment]
> This could occur if there's more than one thread consuming from the queue.
> 
> Also, please update to the latest master, there were some fixes around signals while blocking on the semaphore at one point.

I thought this had been fixed.

B.T.W. If I want to support multiple producers multiple consumers and keep consuming in order, what should I use?

Thanks.

**Comment by MagicKim** [comment]
> > This could occur if there's more than one thread consuming from the queue.
> > Also, please update to the latest master, there were some fixes around signals while blocking on the semaphore at one point.
> 
> I thought this had been fixed.
> 
> B.T.W. If I want to support multiple producers multiple consumers and keep consuming in order, what should I use?
> 
> Thanks.

Have you solved this issue? I am in a single producer and single consumer mode, and I have also encountered this error. I receive moodycamel::BlockingReaderWriterQueue enqueue from multiple network interfaces, and then wait_dequeue in a sub-thread.

**Comment by cameron314** [comment]
> I thought this had been fixed.

The issue was with your example code.

> B.T.W. If I want to support multiple producers multiple consumers and keep consuming in order, what should I use?

You'd need to find another queue implementation. I don't have an MPMC queue with global ordering.

> I receive moodycamel::BlockingReaderWriterQueue enqueue from multiple network interfaces, and then wait_dequeue in a sub-thread.

Are you enqueueing from multiple threads?
