### ISSUE TITLE
Circular Buffer force_enque

### ISSUE THREAD

**Issue by Tetragramm** [cameron314/readerwriterqueue#132]
I'm trying to set up a configurable policy for what happens when a system operating on live data starts to back up.
One of the obvious policies is to drop the oldest data and continue on, but there's no thread-safe way to do this with the circular buffer (as-is anyway).

So my question is: Is the following code a safe way to do this?  Or do I need to add an almost never used and almost never-contested lock to make it work?
Truly, the lock should be fine, but I want to do this the lock-free way if I can.

``` cpp
template <typename U>
void force_enqueue(U &&item)
{
  if (!slots_->tryWait())
  {
    std::size_t i = nextItem++;
    T &element = reinterpret_cast<T *>(data)[i & mask];
    element.~T();
    std::size_t j = nextSlot++;
    new (reinterpret_cast<T *>(data) + (j & mask)) T(std::forward<U>(item));
  }
  else
  {
    inner_enqueue(item);
  }
}
```

**Comment by cameron314** [comment]
A few notes:
- There's a race between no slots being available and overwriting the oldest element
- More generally, there's a race between the producer overwriting the oldest element and the consumer also trying to dequeue it
- This code is not exception safe (I believe neither is mine, to be fair)
- I don't quite understand how this would fit into the existing code (given there's no block manipulation)

**Comment by Tetragramm** [comment]
Hmm.  I get the second race, (IE: the producer pauses, the consumer reads the entire queue including a possibly in mid modification oldest element).

I'm not sure what you mean by the first one though.  Do you mean that an element might be overwritten even though a free slot has opened up since the semaphore was checked?  Or is there a way for the consumer to be reading the element as it's being overwritten?

**Comment by cameron314** [comment]
The first race is a subset of the second, so it's not really important, but what I was referring to was:
1. `slots_->tryWait()` fails, so the producer enters the `if`
2. Meanwhile, the consumer consumes a single element (the oldest one, since this is a FIFO queue)
3. The producer now either destructs the next element (despite a slot being available) or double-destructs the same element that was just consumed

**Comment by Tetragramm** [comment]
I see where my mistake is now.  I knew destructing two elements at once is possible, and just the cost of multi-threaded programming, but I thought double-destructing was impossible because size_t increment is atomic.  
Unfortunately, that is true only for specific architectures, so it's not safe to rely on.

Thank you for your help and advice.

**Comment by cameron314** [comment]
size_t increment is not atomic but `std::atomic<size_t>` increment is. Not sure how this would help here though.
