### ISSUE TITLE
peek() method for BlockingReaderWriterCircularBuffer?

### ISSUE THREAD

**Issue by f18m** [cameron314/readerwriterqueue#140]
Hi,
I'm trying to replace the ReaderWriterQueue with BlockingReaderWriterCircularBuffer (my idea is that with the latter I can remove some arbitrary sleep() calls in producer/consumer threads).
However I noticed that there is no such thing like ReaderWriterQueue::peek() defined in BlockingReaderWriterCircularBuffer. Is it possible to add such API or is there a good reason why it's missing? 

Thanks!

**Comment by cameron314** [comment]
I *think* it could be implemented. Depends whether `items->availableApprox()` being non zero guarantees an item is there, which I believe is the case.

**Comment by cameron314** [comment]
Yeah, it would work because the consumer thread necessarily sees its own decrements on that semaphore, so if it sees the semaphore at non-zero, there must still actually be an element.

**Comment by cameron314** [comment]
Added. Feel free to reopen if you find an issue with it.

**Comment by f18m** [comment]
that was really fast, thanks a lot for the prompt response and implementation! will check it out ASAP
