### ISSUE TITLE
Circular Buffer Doesn't Overwrite Old Data

### ISSUE THREAD

**Issue by mreutman** [cameron314/readerwriterqueue#141]
Hello,

Just found your project and am interested in possibly using it within my code. One thing I'm trying to understand is if the circular buffer will overwrite old data that hasn't been dequeued yet when new data is enqueued. Through looking at the code and making a small demo application for myself, it seems that the circular buffer returns `false` when trying to enqueue new data when at capacity. Currently I use Boost's circular buffer which has the behaviour of `push_back` tossing out the old item, adding the new one, and internally adjusting the circular buffer's head & tail.

I think I saw a comment in one of the issues here which lead me to believe this behaviour is possible with the circular buffer, so perhaps I'm misunderstanding or misusing your code.

Thanks in advance for the help!

**Comment by cameron314** [comment]
Yeah, that's not the API provided by the current implementations here. Would have to think about how best to protect an element from being overwritten while being consumed by the other thread.

**Comment by mreutman** [comment]
@cameron314 I ended up making use of the circular buffer as written. After looking into your code & the design choices, I think I better understand the difficulties of overwriting old data. Thanks for your time.
