### ISSUE TITLE
Supported platforms/operating systems?

### ISSUE THREAD

**Issue by KoenT-SS** [cameron314/readerwriterqueue#150]
Hi,

thank you for publishing your work and for making it available under a nice license!

I saw this statement in the read me page:

_"The queue should only be used on platforms where aligned integer and pointer access is atomic; fortunately, that includes all modern processors (e.g. x86/x86-64, ARM, and PowerPC). Not for use with a DEC Alpha processor (which has very weak memory ordering) :-)
Note that it's only been tested on x86(-64); if someone has access to other processors I'd love to run some tests on anything that's not x86-based."_

Is this still accurate?

For now, I'm working on Windows x86(-64), but in the future macOS (Intel and Apple silicon), iOS/iPadOS and Android is planned too.

Do you know if your code works as expected on modern macOS (Intel and Apple silicon), iOS/iPadOS and Android devices, because it has sufficiently been used in the wild on these platforms too by now?
Or is the statement still accurate in that it _theoretically should_ work, but has not been tested yet on these platforms?

Thanks,
Koen

**Comment by cameron314** [comment]
I have not personally tested it on other platforms. Others have used it on Mac and probably ARM. I'd be very surprised if you ran into issues.

**Comment by cameron314** [comment]
Closing for now
