### ISSUE TITLE
Running benchmark - gcc doesn't link pthread

### ISSUE THREAD

**Issue by mintyc** [cameron314/readerwriterqueue#16]
On ubuntu 1404 LTS with gcc 4.8.2

Clone repo
cd benchmarks
make
< compiles with 
g++ -std=c++11 -Wpedantic -Wall -DNDEBUG -O3 -g -lrt bench.cpp ../tests/common/simplethread.cpp systemtime.cpp -o benchmarks -pthread
>
./benchmarks
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted

ldd benchmarks shows no pthread lib

Looks like this might be related to this bug (doesn't link pthread)
https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1228201

so added '-Wl,--no-as-needed' to makefile to work around. Now runs.

See also http://stackoverflow.com/questions/19463602/compiling-multithread-code-with-g
[Shows a simple example that fails]

Not sure if there is a better solution?
(separating compilation from linking and passing -pthread to both also works)

Looks like ubuntu/debian toolchain pass --as-needed to the linker, but the benchmark libs don't correctly propagate the need for libpthread so it gets removed at link unless we tell the linker NOT to cull 'unnecessary' libs.
http://gcc.gnu.org/ml/gcc-help/2010-12/msg00338.html

Arguably the fix is to make sure gcc doesn't assume that pthread isn't needed, rather than the workaround but I'm a bit bemused that it fails in the first place (see SO simple example that also fails)

**Comment by cameron314** [comment]
Fascinating. Since this appears to be a platform-specific bug, and `--no-as-needed` is benign, I'm inclined to just add the flag and leave it at that. Will do soon, thanks for opening an issue!

**Comment by cameron314** [comment]
Done!
