### ISSUE TITLE
atomicops.h on VS2015

### ISSUE THREAD

**Issue by mintyc** [cameron314/readerwriterqueue#17]
I notice that atomicops.h implements atomic_*_fence on all _MSC_VER

Is there any benefit to make this conditional on say _MSC_VER < 1900 as I think its all present and correct in `<atomic>` for VS2015

**Comment by cameron314** [comment]
Probably a good idea. It might take a little while before I get around to it, though.

**Comment by mintyc** [comment]
I made the change but no significant difference to benchmark numbers (MSVS 2015 CTP 5)

Incidentally profile guided optimisation improves the folly scores by 10% but rest are unaffected

**Comment by cameron314** [comment]
Interesting, I never thought to try PGO.

I've committed the change (along with a blocking version of the queue) that uses the `std::` fences on VS2012+. Thanks for opening this issue!
