### ISSUE TITLE
segfaults when compiled with static

### ISSUE THREAD

**Issue by joeyo** [cameron314/readerwriterqueue#18]
The unit tests / stab tests segfault for when compiled with `-static` on gcc 4.7.2 (Debian Wheezy) and gcc 4.9.2 (Debian Jessie). This is apparently due to a failure to link properly with pthreads when statically linked. Compiling with `-Wl,-u,pthread_cancel,-u,pthread_cond_broadcast,-u,pthread_cond_destroy,-u,pthread_cond_signal,-u,pthread_cond_wait,-u,pthread_create,-u,pthread_detach,-u,pthread_cond_signal,-u,pthread_equal,-u,pthread_join,-u,pthread_mutex_lock,-u,pthread_mutex_unlock,-u,pthread_once,-u,pthread_setcancelstate` resolves the segfault by forcing linking, [it seems](http://stackoverflow.com/questions/7090623/c0x-thread-static-linking-problem). I make this change in cecd5c0adb9f878eb7ff88e9a59ff49131ed67c8.

Alternatively, simply don't use `-static`.

As Jessie was only just released, people may be running into this for a few years, so hopefully this will save someone some grief.

**Comment by cameron314** [comment]
Aw, yeah, sorry about that. Everything I read says not to use `static` on Linux. I'll remove it. (Still handy on Windows with MinGW though.)

Thanks for opening an issue!
