### ISSUE TITLE
Feature request for blocking queue - controlling wait

### ISSUE THREAD

**Issue by mintyc** [cameron314/readerwriterqueue#19]
When dequeuing on a potentially blocking queue it is often useful to implement a timeout or more generally have a means to wake up the waiting receiver ideally without sending a 'fake' packet through. 

For the send side, could we expose a signal() function to call sema.signal() and remove the check in the dequeue functions that expect a woken thread to always succeed in inner.try_dequeue

This does however change the stated description of try_dequeue and wait_dequeue so I wonder if there is a better way....

[Could implement a 'dummy msg', 'timeout' and/or 'done' command packet but that affects the generic nature of the queue's payload template as we'd need to define and recognise those commands.]

	AE_FORCEINLINE void signal()
	{
		sema.signal();
	}

	template<typename U>
	bool try_dequeue(U& result)
	{
		if (sema.tryWait()) {
			return inner.try_dequeue(result);
		}
		return false;
	}

	template<typename U>
	void wait_dequeue(U& result)
	{
		sema.wait();
		bool success = inner.try_dequeue(result);
		// TODO what to do with result??? Can't convey 'failed' wait
	}

**Comment by cameron314** [comment]
Hmm, this one's tricky. I would rather expose an overload of `wait_dequeue` that accepts a timeout parameter, but of course that necessitates support at OS semaphore level. I'll look into this and see what I can do.

**Comment by xeoshow** [comment]
Strongly need this feature, when this feature could be available? Thanks!

**Comment by cameron314** [comment]
@xeoshow: My personal life is busy at the moment, so not for at least three weeks, probably more.
What platform(s) are you on? I'm not sure this can be easily implemented on Mac OS X.

**Comment by xeoshow** [comment]
Thanks for kind reply! I am on windows platform, is it possibly supported?

**Comment by cameron314** [comment]
Yes, when I get around to this, Windows and Linux will have support first.

**Comment by cameron314** [comment]
Just an update: This is finally in the pipeline. Support for timeouts coming soon to a repository near you.

**Comment by xeoshow** [comment]
Any news now? :+1:

**Comment by cameron314** [comment]
ETA ten minutes :-)

**Comment by cameron314** [comment]
All right, I'm terrible with estimates. Done now! Let me know if you come across any issues.
