### ISSUE TITLE
Using the consumer without a busy wait loop

### ISSUE THREAD

**Issue by GP-GPU** [cameron314/readerwriterqueue#28]
Hi,
I have an infinite stream of messages which I enqueue using a producer.
Now, I create a consumer in a separate thread like so: 
``
auto qSubscriber=[](moodycamel::ReaderWriterQueue<std::string> &q, zmq::socket_t *pub) {
    std::cout <<"qSubscriber"<< std::endl;
    std::string m;
    bool succeeded;
    while (true) { // How can I avoid this?
        //sleep(1);
        succeeded=q.try_dequeue(m);
        if(succeeded) {
            zmq::message_t message(m.length());
            memcpy(message.data(), m.c_str(), m.length());
            //std::cout << "receiving :" << m << std::endl;
            pub->send(message);
        }
    }

};
``
Is there a way to avoid the loop and use a notification whenever there are new items in the queue?

Thanks,

**Comment by cameron314** [comment]
There is! You're looking for the blocking version of the queue (as mentioned in the README).

Example:

    while (true) {
        q.wait_dequeue(m);
        zmq::message_t message(m.length());
        memcpy(message.data(), m.c_str(), m.length());
        //std::cout << "receiving :" << m << std::endl;
        pub->send(message);
    }

**Comment by GP-GPU** [comment]
Thanks!

A second question. I need to access UUID's very fast. 

If I generate them on the fly, these are the timing results:
avg(call/sec)=71332.914
 elapsed usec=7009387
 avg(usec/call)=14.018774
 avg(call/msec)=71.332914

While if i use the readerwriterqueue to De-queue existing UUID's these are the timings which are of course on an order of magnitude faster:
 avg(call/sec)=7.3746313e+08
 elapsed usec=678
 avg(usec/call)=0.001356
 avg(call/msec)=737463.13

Now for the question: if I generate 1 million UUID's and start consuming them, is there an idiom/design pattern that can be used to start en-queuing again once there are, lets say 50% of the original number of items in the readerwriterqueue? 

Best,

**Comment by cameron314** [comment]
Hmm, interesting. I'm not sure how using the queue makes it faster, though? Surely you still have to generate them one way or another?

But yes, you can use `size_approx()` to find out how many items there are in the queue. This is not particularly efficient with the normal (non-blocking) version of the queue, since it traverses every block within the queue. However, the blocking version keeps a separate counter of the number of elements, and so its version of this method is quite efficient and can be called periodically from your loop.

**Comment by GP-GPU** [comment]
Thanks, I am using the blocking version :)
Sure, I pre-generate all the UUID's so that I have everything in memory.
