### ISSUE TITLE
Assertion failed: (!inSection && "ReaderWriterQueue does not support enqueuing or dequeuing elements from other elements' ctors and dtors"), function ReentrantGuard, 

### ISSUE THREAD

**Issue by GP-GPU** [cameron314/readerwriterqueue#29]
Hi,
The code that generated this error:

    auto asyncMonitor =[](moodycamel::BlockingReaderWriterQueue<std::string> &q) {
        while (true) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
            std::cout<<std::chrono::system_clock::now().time_since_epoch().count() << std::endl;
            if(q.size_approx()<MAX_ITEMS/10) {
                std::cout<<"adding elements ...";
                for(int i=0;i<MAX_ITEMS/2;i++) {
                    bool succeeded = q.try_enqueue(sole::uuid4().str());
                    //std::cout<<"adding UUID element:"<<i<<std::endl;
                }
            }
        }
    };

The code is invoked as follows: 

    auto dummy2=std::async(std::launch::async,[&q](){
        asyncMonitor(q);
    });

Any idea why this is happening?

**Comment by cameron314** [comment]
Well, the message in the assertion is definitely not what is happening here (`std::string` does not know anything about the queue, obviously).

Is it possible that you have another thread enqueueing to the same queue in parallel somewhere else? Or two threads dequeueing in parallel?

As an aside, is there any particular reason you're passing GUIDs around as strings?

**Comment by cameron314** [comment]
And just to make sure, this is a debug build, right?

**Comment by GP-GPU** [comment]
"Is it possible that you have another thread enqueueing to the same queue in parallel somewhere else? Or two threads dequeueing in parallel?"
Yes, it is very probable. Why does this impose a problem? I am using the multiple reader multiple writer queue no?.

It is a release build like so:
set(CXX_RELEASE_FLAGS = -O3 -march=native)

Thanks,

**Comment by cameron314** [comment]
Aha :-) No, you are not. This is a single producer, single consumer queue (SPSC). My MPMC queue is [here](https://github.com/cameron314/concurrentqueue).

You should define `NDEBUG` for a release build. Otherwise you'll get all the assertions and a few extra checks compiled in.
