### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by richwu** [cameron314/readerwriterqueue#30]
atomicops.h:477:30: error: 
     use of undeclared identifier 'errno'
                        while (rc == -1 && errno == EINTR);
and also the compiler complained undeclared identifier 'EINTR'

My build environment is Ubuntu 14.04, Clang++ 3.7.1
Ubuntu clang version 3.7.1-svn253742-1~exp1 (branches/release_37) (based on LLVM 3.7.1)
Target: x86_64-pc-linux-gnu
Thread model: posix

I tried adding #include <errno.h> in atomicops.h, still same problem.

**Comment by cameron314** [comment]
Sorry about that. Thanks for opening an issue!
This is definitely caused by a missing `#include` -- I added one for `cerrno`. I'm not sure why it didn't work for you when you tried the same. Could you test again with the tip to double check?

**Comment by richwu** [comment]
I tested it. Everything seems fine.

**Comment by cameron314** [comment]
Excellent, thanks :-)
