### ISSUE TITLE
No include of <cstdint> to provide `std::int64_t` et al?

### ISSUE THREAD

**Issue by fake-name** [cameron314/readerwriterqueue#32]
Hi there!

I'm looking at using this queue for some code, and it's not building under MSVS2013 x64. The issue is that the fixed-width integer types in `atomicops.hpp` are not available because `<cstdint>` is not included, apparently.

Adding `#include <cstdint>` to the top of `atomicops.hpp` fixes the issue easily.

```
Error	1	error C2039: 'uint64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	403	1	xxx
Error	2	error C2039: 'int64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	569	1	xxx
Error	3	error C2039: 'int64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	634	1	xxx
Error	4	error C2039: 'uint64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	403	1	xxx
Error	5	error C2039: 'int64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	569	1	xxx
Error	6	error C2039: 'int64_t' : is not a member of 'std'	c:\code\xxx\src\lib\atomicops.hpp	634	1	xxx

```

Note that I've renamed `atomicops.h` `atomicops.hpp` to match my project's naming standards, but I can't imagine that change would cause this behaviour.

**Comment by cameron314** [comment]
Oops, I forgot this header wasn't already included when I added those uses of (u)int64 the other day. Fixing! :-)

**Comment by cameron314** [comment]
Sorry about that!

**Comment by fake-name** [comment]
Sweet! I think this is the first time I've had a bug fixed basically before I finished copy-editing the bug report!

**Comment by cameron314** [comment]
Haha, it's a nice change for me too. The longer bugs/features normally take me months to get around to. Small things I can do!
