### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by peters** [cameron314/readerwriterqueue#36]
Hi,

Could you please tag a release of this repository so that I can submit it as a package to https://github.com/Microsoft/vcpkg ? 👍

**Comment by cameron314** [comment]
Cool :-) I can't tag a release as-is because there's known bugs that I'm working on fixing.
It's been at the back of my mind for a while, though. Maybe I'll do a beta release?

**Comment by cameron314** [comment]
Oops, mixed up repositories, thought this was for the concurrentqueue. Yes, I'll do a release right now, it's production quality as far as I know.

**Comment by cameron314** [comment]
There you go, done! For the package, the following four files are all that should be in it: atomicops.h, readerwriterqueue.h, README.md, and LICENSE.md.

**Comment by peters** [comment]
Thanks! I have to say you have done an awesome job with this library. I've been using it for over a year now and it most certainly does not qualify as beta quality 🍻

**Comment by cameron314** [comment]
This one, I agree, I was thinking of https://github.com/cameron314/concurrentqueue, which seems to have a new issue opened every week ;-)

Thanks!
