### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by breznak** [cameron314/readerwriterqueue#37]
Hi @cameron314 , 

thank you for your work here! :+1: I'm wondering what is the status of the repository? as most issues got stuck 1-2 years ago.

**Comment by cameron314** [comment]
The status is released with no known bugs, i.e. in maintenance mode. I don't have a lot of time to work on open source projects but I'll occasionally tweak something or add a small bugfix or enhancement.

I had forgotten to close an issue, but the other two are small enhancements that I'd like to add eventually but haven't gotten around to yet.
