### ISSUE TITLE
[enh] Implement `push_back` so fast appending of a whole vector is possible

### ISSUE THREAD

**Issue by breznak** [cameron314/readerwriterqueue#38]
It would be a nice enhancement to a speed-oriented queue in scenarios where user wants to append several items at a time. As in the answer why it is currently not happening + possible workaround. 

https://stackoverflow.com/questions/1723515/insert-into-an-stl-queue-using-stdcopy

**Comment by cameron314** [comment]
Sorry, this queue is not intended to be STL-compatible.
Appending multiple elements is not any faster with a `back_inserter` anyway, just slightly less code to write.
