### ISSUE TITLE
Use std::shared_ptr in readerwriterqueue

### ISSUE THREAD

**Issue by yuanyinchun** [cameron314/readerwriterqueue#39]
Hi,
I want to push std::shared object to lockfree queue. After some digging, I found out boost::lockfree::queue cannot use std::shared as Type.  So I wander is it possible to use std::shared_ptr in this queue?  

Here is my usage scenario:
Four thread, one thread produce data, other three thread each has a  lock free queue.
When data production thread generate new data , I use std::shared_ptr to wrap the new data, then put
std::shared_ptr object into three consume thread's lockfree queue. Consume thread is a while loop, pop data from its lockfree queue, then read the data(no modification).

Will data pointed by std::stared_ptr correctly destructed after pop  from all three lockfree queue?

**Comment by cameron314** [comment]
Yes, this is fully supported. Normal object construction/destruction semantics are followed.

Each of the three queues will contain a shared_ptr on the object, which will be assigned to the output parameter of the try_dequeue method before being destructed (i.e. the shared data will maintain at least one reference count until all three consumers are done with it).

**Comment by yuanyinchun** [comment]
Thanks! I will give a try.
