### ISSUE TITLE
Crashing on Linux whenever I try to do a try_dequeue on an empty readerwriter queue.

### ISSUE THREAD

**Issue by sirilvk** [cameron314/readerwriterqueue#43]
Hi,
Whenever I try to do a try_dequeue on an empty readerwriter queue my code crashes at moodycamel/readerwriterqueue.h:239. Though the queue is empty it still tries to go ahead and dequeue the element. Can you please help? My code is actually looping on the try_dequeue and most of the time it works fine and suddenly it crashes at result = std::move(*element); on line 239 even though the queue is empty. Please help.

Thanks,
Siril.

**Comment by sirilvk** [comment]
Extremely sorry for raising this issue. The issue had nothing to do with your library. Sorry once again.

**Comment by cameron314** [comment]
No worries, glad you found the issue :-)
