### ISSUE TITLE
Queuing raw pointers of memory

### ISSUE THREAD

**Issue by sasmaster** [cameron314/readerwriterqueue#45]
HI.I am trying to understand how to use your queue with pointers to memory .You got a template param which is type.So how does one go with it when the data is a pointer to block of memory which I need to push into queue?

**Comment by cameron314** [comment]
You simply use the pointer type as the template parameter, since it's the type of objects that you're queueing.

Example:

    ReaderWriterQueue<char*> q;

    char* x = malloc(128);
    q.enqueue(x);

    q.try_dequeue(x);
    free(x);
