### ISSUE TITLE
Is it possible to check if same item does not already exists in the queue when adding a new one?

### ISSUE THREAD

**Issue by danechitoaie** [cameron314/readerwriterqueue#47]
I need to pass file paths from one thread to another and it would improve the program if from the produce thread I would add in the queue only if the item is not already there (string representing a path).

So once the consumer thread took that item from the queue it could be added again.

**Comment by cameron314** [comment]
No, sorry, this isn't possible. Every item in the queue would somehow have to be checked, atomically. (There's no internal set representation.)

**Comment by danechitoaie** [comment]
Ok, thanks for the info.
