### ISSUE TITLE
wait_dequeue not waiting in Redhat 7.1

### ISSUE THREAD

**Issue by rahulzbali** [cameron314/readerwriterqueue#48]
i am trying to implementing code but getting following error 

void moodycamel::BlockingReaderWriterQueue<T, MAX_BLOCK_SIZE>::wait_dequeue(U&) [with U = std::shared_ptr<MyObject>; T = std::shared_ptr<MyObject>; long unsigned int MAX_BLOCK_SIZE = 512ul]: Assertion `success' failed.

this code using inside Thread(detached)

**Comment by cameron314** [comment]
Sorry for the delay, I lost some emails at one point and only just noticed this issue.

Can you provide a short reproducible example?

**Comment by rahulzbali** [comment]
Hello,
         I resolve Issue,i will update new Code

**Comment by cameron314** [comment]
Great, thanks. Was it a bug in the queue?

**Comment by rahulzbali** [comment]
Hello,
        its not issue...

          i made some changes in atomicops.h file , reason was while i am
using your .h file in my code(in my code also having semaphore)
because of my Semaphore object, system couldn't differentiate in your
object and my object ..

          system couldn't wait while i am using your .h file

----------------------------
in above code you can see I initialized sema object with mmap & sema
convert into poiter

it easy to system identified your sema object and my sema object

------------------------------


#elif defined(__unix__)
//---------------------------------------------------------
// Semaphore (POSIX, Linux)
//---------------------------------------------------------
class Semaphore
{
private:
    sem_t* m_sema= (sem_t*)mmap(0, sizeof(sem_t), PROT_READ|PROT_WRITE,
MAP_ANONYMOUS|MAP_SHARED, 0, 0 );

    Semaphore(const Semaphore& other);
    Semaphore& operator=(const Semaphore& other);

public:
    Semaphore(int initialCount = 0)
    {
        assert(initialCount >= 0);
        sem_init(m_sema, 0, initialCount);
        //pid_t  pid = fork();
    }

    ~Semaphore()
    {
        sem_destroy(m_sema);
    }

    void wait()
    {
        //
http://stackoverflow.com/questions/2013181/gdb-causes-sem-wait-to-fail-with-eintr-error
        int rc;
        do
        {
            rc = sem_wait(m_sema);
        }
        while (rc == -1 && errno == EINTR);
    }

bool try_wait()
{
int rc;
do {
rc = sem_trywait(m_sema);
} while (rc == -1 && errno == EINTR);
return !(rc == -1 && errno == EAGAIN);
}

bool timed_wait(std::uint64_t usecs)
{
struct timespec ts;
const int usecs_in_1_sec = 1000000;
const int nsecs_in_1_sec = 1000000000;
clock_gettime(CLOCK_REALTIME, &ts);
ts.tv_sec += usecs / usecs_in_1_sec;
ts.tv_nsec += (usecs % usecs_in_1_sec) * 1000;
// sem_timedwait bombs if you have more than 1e9 in tv_nsec
// so we have to clean things up before passing it in
if (ts.tv_nsec > nsecs_in_1_sec) {
ts.tv_nsec -= nsecs_in_1_sec;
++ts.tv_sec;
}

int rc;
do {
rc = sem_timedwait(m_sema, &ts);
} while (rc == -1 && errno == EINTR);
return !(rc == -1 && errno == ETIMEDOUT);
}

    void signal()
    {
        sem_post(m_sema);
    }

    void signal(int count)
    {
        while (count-- > 0)
        {
            sem_post(m_sema);
        }
    }
};

**Comment by cameron314** [comment]
There were some bugs in the semaphore wait code which should now be fixed.
