### ISSUE TITLE
timed_wait fails if tv_nsec is one billion

### ISSUE THREAD

**Issue by Satsuoni** [cameron314/readerwriterqueue#49]
After chasing down a mysterious rare crash in my code, the issue turned out to be that timed_wait in atomicops.h Semaphore implementation returned true without waiting iff  tv_nsec==1000000000. It seems that sem_timedwait "bombs" on that value in addition to any nsec value above that. The fix seems to be replacing 
```
if (ts.tv_nsec > nsecs_in_1_sec) {
```
with
```
if (ts.tv_nsec >= nsecs_in_1_sec) {
```

**Comment by cameron314** [comment]
Nice catch, sorry about that. Will push a fix later today.

**Comment by cameron314** [comment]
Should be fixed. Thanks for investigating and reporting this!
