### ISSUE TITLE
Vector of readerwriterqueue

### ISSUE THREAD

**Issue by metainf** [cameron314/readerwriterqueue#50]
This might be a odd question, but what is the best way to create a vector of the ReaderWriterQueue?
I want to do this because I have a single reader, and multiple writers, but I want to keep the data from  each writer separate. I've tried
```
vector<ReaderWriterQueue<FrameTimestamp> > matQueue;
matQueue.push_back(ReaderWriterQueue<FrameTimestamp> tempQueue(30));
matQueue.push_back(tempQueue);
```
but that throws `error: ‘moodycamel::ReaderWriterQueue<T, MAX_BLOCK_SIZE>::ReaderWriterQueue(const moodycamel::ReaderWriterQueue<T, MAX_BLOCK_SIZE>&) [with T = frameTimestamp_t; long unsigned int MAX_BLOCK_SIZE = 512ul]’ is private
`

**Comment by cameron314** [comment]
Hmm. I'll have to add a move constructor to enable this.

**Comment by metainf** [comment]
Btw, I've gotten it to work for now using a vector of pointers of ReaderWriterQueue.

**Comment by cameron314** [comment]
I've added the ability to move queue objects around, and a unit test. You can now write:

    std::vector<ReaderWriterQueue<FrameTimestamp>> matQueue;
    matQueue.emplace_back(30);

    // ...
    matQueue[0].enqueue(1234);

**Comment by cameron314** [comment]
(Note that the blocking queue version is still not moveable. This is by design and won't change for now.)
