### ISSUE TITLE
BlockingReaderWriterQueue::try_dequeue - assertion

### ISSUE THREAD

**Issue by cdemez** [cameron314/readerwriterqueue#52]
Hi,

Sometimes I got an assertion in "BlockingReaderWriterQueue::try_dequeue", the "assert(success);" failed !

Any idea ?

**Comment by cameron314** [comment]
Well, that's never supposed to happen. Can you provide a sample that reproduces the issue?

**Comment by cdemez** [comment]
I understand... it only happens in our software and I cannot gives you a repro-case! Just for your information ;-)

**Comment by cameron314** [comment]
Alright, well, that's not much to go on. The more information I have the likelier I am to succeed in finding the bug :-)

What platform are you on? Compiler? Optimization settings? Is the type being queued POD or non-POD? How many bytes per object? Block size?

**Comment by rahulzbali** [comment]
cdemez are you using Linux or Windows !

**Comment by cdemez** [comment]
Windows.

Yes I need to create a sample, but for now I got no time. Sorry for that !

**Comment by mjohnson138** [comment]
I am noticing a similar issue on occasion as well. I am running on CentOS Linux release 7.2.1511 (Core) on x86_64 architecture. I have created a sample that will recreate the issue, but since I'm not sure what's causing it, I had to run it overnight before the issue popped up. Apologies if this is simply user error. 

The code was compiled with gcc 7.2.0 with the flags "-std=c++17 -O0 -g -D_DEBUG". The commit hash of the version I'm running is 6e08b92dccc3df39269e9fb528d7d4f5b35fb731. Here is the terminal output and then below is the code:

```
[mjohnson138@mws bin]$ time ./sandbox 
sandbox: /home/mjohnson138/development/platform/ext/moodycamel/readerwriterqueue/include/readerwriterqueue.h:748: wait_dequeue_timed: Assertion `success' failed.
Aborted (core dumped)

real	694m35.746s
user	495m5.396s
sys	11m11.782s
```

```
struct TestEvent {
    TestEvent() { }
    TestEvent(const uint32_t eventType)
        : _type(eventType)
    {
    }

    uint32_t type() const { return _type; }

private:
    uint32_t _type = 0;
};

class TestHarness {
public:
    TestHarness()
        : _isRunning(true)
    {
        _workerThread = std::thread(std::bind(&TestHarness::run, this));
    }

    ~TestHarness() {
        _isRunning.store(false, std::memory_order_release);
        if(_workerThread.joinable())
            _workerThread.join();
    }

    void insert() {
        TestEvent event(0);
        _queue.enqueue(std::move(event));
    }

    int64_t timeoutUsecs() const { return _timeoutUsecs; }

    void run() {
        TestEvent event;
        while(_isRunning.load(std::memory_order_acquire)) {
            const bool itemFound = _queue.wait_dequeue_timed(event, _timeoutUsecs);
            if(!itemFound)
                continue;
        }
    }

private:
    const int64_t _timeoutUsecs = 10;
    std::atomic_bool _isRunning;
    moodycamel::BlockingReaderWriterQueue<TestEvent> _queue;
    std::thread _workerThread;
};

int main(int argv, char* argc[]) {
    TestHarness harness;
    srand(static_cast<uint>(time(NULL)));

    while(true) {
        const int sleepTime = (rand() % 10 + 1) * harness.timeoutUsecs();
        usleep(sleepTime);
        harness.insert();
    }

    return 0;
}
```

**Comment by cameron314** [comment]
There were some bugs in the semaphore code that should now be fixed. Please reopen if the assertion still occurs.
