### ISSUE TITLE
LICENSE.md All Rights Reserved and BSD?

### ISSUE THREAD

**Issue by gitjonathan** [cameron314/readerwriterqueue#53]
Excellent code.  Would love to use it.  There will be a problem with the license if I did.  The copyright statement is fine, but the "All Rights Reserved" statement abrogates the remaining BSD license clauses.  Please consider modifying by removing those three words, then the BSD license is in effect without the confusion.  (i.e. either ALL rights are reserved, or the rights are spelled out by the BSD license).  
Thanks.

**Comment by cameron314** [comment]
"All Rights Reserved" refers to my rights as copyright holder. For example, I could choose to re-license or dual-license a future version of the code. See [here](https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved). As I understand it, the rights to use the software (*your* rights) are then laid out in the license.

I got the "All Rights Reserved" line from the Wikipedia page for the BSD license. I feel more comfortable leaving it that way. If you like, I can explicitly grant you written permission for your particular use.
