### ISSUE TITLE
clear() and reserve() methods proposal

### ISSUE THREAD

**Issue by sasmaster** [cameron314/readerwriterqueue#59]
Hi. First thanks for this wonderful lib. Using it extensively.Now, I added clear() method in my case as I occasionally empty all the data from the queue on  restart of different logic. Currently I do it like this:

	 inline void clear()
	{
		 bool isFull = true;
		 while (isFull)
		 {
			 isFull = this->pop();
		 }
	}

I wonder if you can consider adding something like this (including thread-safety/ or not) so that it becomes a part of the API? 
Another moment,you allow preallocating the storage for the queue,while calling the default constructor. That's a problem if the queue is non pointer (Static) member of a class. In this case I have to switch to dynamic allocation to pass default size into the contructor? That's how I got it,unless I am missing something. Something like reserve() would be helpful
Thanks.

**Comment by cameron314** [comment]
I'll think about adding a `clear_unsafe()` method. You could also do it by assigning an empty queue, e.g. `q = readerwriterqueue<T>();`, though this incurs the cost of an `malloc` and `free`.

If the queue is a non-static member of the class, its constructor can be passed a parameter in the class's initializer list. If it's a static member, the constructor can be given a parameter directly at the point it's defined.

**Comment by sasmaster** [comment]
Hmm,indeed...
Didn't think of constructor initialization list. Ok,fine,then I can live without reserve()  ))

Thanks!

**Comment by FilenkovMaxim** [comment]
> about adding a clear_unsafe() method

I endorse feature request and thanks for the good job!

**Comment by cameron314** [comment]
I've switched to maintenance mode and won't be adding new features to the queue.
