### ISSUE TITLE
Assertion failed: (!inSection && "ReaderWriterQueue does not support enqueuing or dequeuing elements from other elements' ctors and dtors")

### ISSUE THREAD

**Issue by nkari82** [cameron314/readerwriterqueue#60]
This is my pseudo code using asio.

```
asio::strand strand;
ReaderWriterQueue<int> queue;

void doSomething()
{
  strand.post([]
  {
      int* value = queue.peek();
      // Do something
  }
}

// EntryPoint
void Enqueue(int value)
{
      queue.enqueue(value);
      Process();
}


void Process()
{
  strand.post([]
  {
      int* value = queue.peek();              // <-- assert failed!!!!!
      if(value)
      {
          // Do something
          queue.pop();
      }
  });
  doSomething();
}
```

doSomething() and Process() may work in different threads, but they are obviously being synchronized to asio::strand.

whats wrong?

**Comment by cameron314** [comment]
That assertion indicates that you're either enqueueing or, as in this case, dequeueing from two different threads at the same time (or reentrantly as the message somewhat misleadingly indicates).

I'm not familiar with `asio::strand`, though a cursory look at the documentation would lead me to believe that the strand should indeed only invoke one handler at a time.

Is it possible that you're also accessing the queue outside of the strand? If you put breakpoints in the strand handlers, are they running on different threads?

**Comment by nkari82** [comment]
added NDEBUG

I was running for 10 hours and I had no problems.

**Comment by qwe40954** [comment]
I also got this problem. I have two thread, one is producer and another is consumer. When using try_dequeue,  I got this alarm. But if I added usleep in my loop after calling try_dequeue, it disappared. That's really confused me.

**Comment by cameron314** [comment]
If you have this assert, there's necessarily a bug (usually in the calling code). Can you post a simplified version of your code? What are the callstacks in the debugger at the time the assertion triggers?

**Comment by fake-name** [comment]
I'm hitting this as well, in a context that I think *should* be forced to be serialized.

In any event, could you consider changing the error message?

`ReaderWriterQueue does not support enqueuing or dequeuing elements from other elements' ctors and dtors"` implies constructors/destructors are involved, when apparently the check is actually for concurrent writes/reads. 

Maybe a error like 'ReaderWriterQueue does not support multiple enque or deque operations in parallel"?

**Comment by cameron314** [comment]
Hmm, the message *is* confusing. I'll fix that :-)

You're right about the threading model too -- technically there's no reason the consumer/producer roles can't be migrated to another thread. However, to do so safely would indeed require carefully placed memory barriers in the user's code (and obviously some synchronization to prevent access from multiple threads at once to the either enqueue or dequeue), hence the wording in the README.

**Comment by fake-name** [comment]
> You're right about the threading model too -- technically there's no reason the consumer/producer roles can't be migrated to another thread. However, to do so safely would indeed require carefully placed memory barriers in the user's code (and obviously some synchronization to prevent access from multiple threads at once to the either enqueue or dequeue), hence the wording in the README.

Hmm, can you provide any guidance on what would be required WRT memory barriers, etc..? 

Basically, I have a project where I have a large set of `executable_task_t`, across which a pool of threads continually iterates and attempts to execute. Each task is internally serialized with a mutex, so I can make guarantees that the task itself (which then consumes/produces from ReaderWriterQueues) is explicitly serialized. However, I don't have any control over *which* worker thread it will execute in. 

Basically, I think I wind up with something very similar to `asio`'s `strand` mechanism - serialized execution of individual task-series in a cooperative multiprocessing context.

On the other hand, I don't pretend to have a great understanding of lock-free programming (at least on x86. I've done it a bit on bare-metal/embedded ARM), so I wouldn't really know where to start to validate that the readerwriterqueue is safe in this context.

**Comment by cameron314** [comment]
The barriers required depend on how you're doing the synchronization to ensure that the methods are not being called in parallel. If you're synchronizing via a mutex, the mutex itself takes care of all the necessary memory barriers when passing from one mutex-protected region to another.

**Comment by fake-name** [comment]
> If you're synchronizing via a mutex, the mutex itself takes care of all the necessary memory barriers when passing from one mutex-protected region to another.

Ah, great! That's exactly what I needed to know. Thanks!
