### ISSUE TITLE
Semaphores trying to move/copy atomics.

### ISSUE THREAD

**Issue by ninnghazad** [cameron314/readerwriterqueue#61]
I had to change the weak atomic to do a load() in the copy and move operators, because on my platform (linux,g++ 7,c++17) std::atomic may not be copied or moved directly.
like: 
`
 weak_atomic(weak_atomic const& other) : value(other.value.load()) {  }
        weak_atomic(weak_atomic&& other) {
                value = other.value.load();
        }
`
otherwise BlockingReaderWriterQueue would not compile while trying to move it about.
(i also deleted the copy constructor/operator on the queue instead of having it be private, but i am too lazy to undo the change and check if this also had to do with it not compiling)

**Comment by cameron314** [comment]
Looks like a bug, thanks. Will fix soon.

**Comment by JackYoustra** [comment]
Any progress? I'm in a similar situation (same platform) and was wondering what the proper way of doing it is. If it's @ninnghazad 's way (or if @ninnghazad has verified that this way works correctly), then I can just go with that.

**Comment by ninnghazad** [comment]
@JackYoustra  i haven't had any problems so far with the changes i made. so the changes seem to be working, if they are correct - as in the proper way to do it - i can't say. i hadn't bothered to check if this would fit with the style or intent of the rest of the code - just wanted it to quickly work.

**Comment by cameron314** [comment]
Sorry everyone, been neglecting my GitHub. I'll commit a fix today. I think @ninnghazad's code is correct, but I'll double check before integrating it.

**Comment by JackYoustra** [comment]
Calling move on a BlockingReaderWriterQueue still doesn't work (the lightweight semaphore can't be moved). I don't know enough about concurrency about how to safely address it, and I'm unsure if the semaphore can even be moved. Any advice?

**Comment by ninnghazad** [comment]
@JackYoustra Can you provide a minimal (non)working example of the problem? 
i checked what it was that i needed the fix for, and it seems i wrote a processing queue for an offscreen render pool. the problem was that adding workers (which have a BlockingReaderWriterQueue member) to the pool's vector-of-worker-threads. however, after the fix i was able to smoothly add workers using pool.emplace_back() either by in-place construction or moving. anyway - drop some source and i'd find some time to see if i can spot anything.

**Comment by JackYoustra** [comment]
Sure! I'm looking at the ConcurrentLimitedPersetAdapter in [this file](https://github.com/blacksmithgu/compressed_cache/blob/master/src/adapters/perset_adapter.hpp). It has a problem with emplace_back.

You can reproduce a similar issue by changing the tests in [unittest.cpp](https://github.com/cameron314/readerwriterqueue/blob/master/tests/unittests/unittests.cpp) line 543 from ReaderWriterQueue to BlockingReaderWriterQueue

**Comment by cameron314** [comment]
The `BlockingReaderWriterQueue` is now movable.
