### ISSUE TITLE
wait_enqueue method

### ISSUE THREAD

**Issue by edenzik** [cameron314/readerwriterqueue#63]
Hope to get around to doing this at some point - but it would be helpful to have a function `wait_enqueue` which would block until the queue has sufficient capacity to insert an element. This might actually be quite simple, but thought i'd post here to see if anybody else would find this useful. 

It is better than adding an external condition variable (in the caller to the library) because AFAIK we can use the simple semaphore to do the same thing wait_dequeue does, except by the enqueuing thread.

**Comment by cameron314** [comment]
See also #63.

**Comment by cameron314** [comment]
True. Although come to think of it, the caller can't implement the semaphore wait themselves because dequeuing an element doesn't necessarily make room for another element to be enqueued (unless both the reader and the writer were already in the same block).

**Comment by cameron314** [comment]
You can leave this open if you want, #62 was already closed.
