### ISSUE TITLE
Support operator==?

### ISSUE THREAD

**Issue by fake-name** [cameron314/readerwriterqueue#72]
I'm working on a project where I have what is basically a dynamically reconfigurable data flow graph, where the graph edges are all `readerwriterqueues`.  Each node has a `std::list<std::reference_wrapper<moodycamel::ReaderWriterQueue<QUEUE_TYPE> > >` of queues it's output is connected to.

Now, I'd like to be able to, given a specific queue, remove it from the output list. However, `readerwriterqueue` doesn't define an operator==, so I have no way of iterating over the list and removing the relevant queue, barring adding additional metadata to the output list.

So, given the above, is there any way `readerwriterqueue` could support `operator==`?

I don't pretend to understand the internals well enough to  know how to implement something like this myself. Would simply comparing `frontBlock` and `tailBlock` be sufficient?

**Comment by cameron314** [comment]
I don't think it makes sense to be able to compare queue objects, since they can't be copied (and will thus never be the same queue).

In your case, you want to compare *references* to the queue. You can do this by comparing the pointers of each referenced object to see if they're actually the same object being referenced:

    bool sameObj = &wrapper.get() == &otherWrapper.get();

**Comment by fake-name** [comment]
It's more accurate to say I want to compare `std::reference_wrapper`s to see if they point to the same or different queues. 

I considered  pointers, but that just didn't seem like it a correct solution (I generally try to avoid pointer hijinks whenever possible when writing c++).

> I don't think it makes sense to be able to compare queue objects, since they can't be copied (and will thus never be the same queue).

Doesn't [ReaderWriterQueue define a copy operator](https://github.com/cameron314/readerwriterqueue/blob/master/readerwriterqueue.h#L175)

**Comment by cameron314** [comment]
That is a move constructor. Comparing pointers to determine object identity is [perfectly acceptable](https://stackoverflow.com/a/16843956/21475) in C++.

**Comment by fake-name** [comment]
Huh, I thought  [`ReaderWriterQueue(ReaderWriterQueue&& other)`](https://github.com/cameron314/readerwriterqueue/blob/master/readerwriterqueue.h#L150) was the move constructor. Isn't `operator=()` the copy assignment operator? Or is it the copy assignment operator for ReaderWriterQueue actually does a move?

Anyways, thanks for the help. Using raw pointers in c++ still makes me feel weird, but I probably just need to get over it.

**Comment by cameron314** [comment]
That is indeed the move constructor, I misread the code, sorry.
`operator=` here is the move-assignment-operator (still no copy, sorry).
