### ISSUE TITLE
coredump on AS7

### ISSUE THREAD

**Issue by chengm349** [cameron314/readerwriterqueue#75]
My env is 

Linux MTSProd.mtsbullion.com 3.10.0-862.3.3.el7.x86_64 #1 SMP Wed Jun 13 05:44:23 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

gdb traceback:
#0  0x00007f7fb41ae8e3 in _IO_flush_all_lockp () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f7fb416889d in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f7fb41a9cc7 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f7fb41b3c16 in _int_malloc () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f7fb41b67dc in malloc () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007f7fb4a74f5d in operator new(unsigned long, std::nothrow_t const&) () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x000000000050d1ab in SgeProcessor::Enqueue (this=0x2752bc0, pBuffer=0x7f7f94017a20) at SgeProcessor.cpp:89
        __PRETTY_FUNCTION__ = "void SgeProcessor::Enqueue(GrowingStr*)"
        p = <optimized out>
#7  0x00000000004d471b in sge_recv_msg (msg=<optimized out>, type=<optimized out>, con_len=<optimized out>, ctx=<optimized out>) at SgeProxy.cpp:81
        pGrowingStr = 0x7f7f94017a20
        recv_msg_len = 84402
        ret = <optimized out>
        pctx = <optimized out>
        ptr = 0x2752bc0
        __PRETTY_FUNCTION__ = "void sge_recv_msg(const char*, int, unsigned int, void*)"

function SgeProcessor::Enqueue(GrowingStr*) impl:

void SgeProcessor::Enqueue(GrowingStr* pBuffer)
{
    SGE_ASSERT(pBuffer, "nullptr of pBuffer");
    SgeTagDecoder* p= new (std::nothrow) SgeTagDecoder(pBuffer);
    if (p) m_sgeMsgQueue.enqueue(p);
    else FT_ERROR << "failed to create SgeTagDecoder decoder" << endl;
}

m_sgeMsgQueue definition:

moodycamel::BlockingReaderWriterQueue<SgeTagDecoder*>   m_sgeMsgQueue;

my SgeProcessor runs  within its own thread to clear the queue:

void SgeProcessor::OnRunIncoming()
{
    ::BlockAllSignalsOnThread();
    m_run.exchange(true);
    Ft_INFO << "starting SgeProcessor thread" << endl;
    while (m_run) {
        SgeTagDecoder* pDecoder = nullptr;
        if (m_sgeMsgQueue.wait_dequeue_timed(pDecoder, std::chrono::milliseconds(5)))
        {
            if (pDecoder)
            {
                std::unique_ptr<SgeTagDecoder> deleter(pDecoder);
                std::size_t nProcessedChars = pDecoder->ParseTag();
                if (pDecoder->GetMsgLength() == nProcessedChars)
                {
                    Process(*pDecoder);
                } else {
                    FT_ERROR << "message len is " << pDecoder->GetMsgLength() 
                            << " and processed len is " << nProcessedChars << endl;
                }
            } else {
                Ft_FATAL << "nullptr decoder" << endl;
                break;
            }
        }
        
        …...
    }
    FT_INFO_LGT << "SgeProcessor thread exited" << endl;
}

**Comment by cameron314** [comment]
Not sure what to make of this. It looks like your heap is getting corrupted? Why do you suspect the queue is what is causing the corruption?

**Comment by chengm349** [comment]
not sure. maybe you are right. just to see any possible advice from other users of the lib. we can close it first.
