### ISSUE TITLE
try_dequeue_bulk

### ISSUE THREAD

**Issue by CristoferMartins** [cameron314/readerwriterqueue#76]
Its possible to add to this queue the try_dequeue_bulk method? I know it exists in the ConcurrentQueue but in my usage there will be only one producer and one reader(which will read them in a bulk).

**Comment by cameron314** [comment]
I think I could do this, but I don't have the time at the moment, sorry.

**Comment by CristoferMartins** [comment]
@cameron314 its possible to add it now?

**Comment by cameron314** [comment]
Sorry :-/ At this point I'm just maintaining the existing code and not adding new features.

**Comment by NikitaMishin** [comment]
Is this could be implemented similarly to https://github.com/cameron314/concurrentqueue ? Is this could enhance noticeably speed?

**Comment by cameron314** [comment]
The implementation would be different because the internal design of the queues are different, but the general idea is the same. However, the gain in performance would be less drastic than with the multi-producer, multi-consumer queue.

**Comment by NikitaMishin** [comment]
thank you for your fast response and for sharing your thoughts!
