### ISSUE TITLE
wait_enqueue() if queue is full?

### ISSUE THREAD

**Issue by helloearth012** [cameron314/readerwriterqueue#83]
Is a symmetric API wait_enqueue() necessary as it has wait_dequeue(). 
Let's say we set the max size of queue to 10, when the 11th comes in, wait_enqueue() should wait until dequeue() takes item from queue, there is room for new item to be pushed in.

**Comment by cameron314** [comment]
The problem is that it's not a simple ring buffer, so even if one element is dequeued  there's not necessarily room for one more to be enqueued (yet).

**Comment by helloearth012** [comment]
> The problem is that it's not a simple ring buffer, so even if one element is dequeued there's not necessarily room for one more to be enqueued (yet).

Thanks a lot for your reply. In some cases, user may want to limit the  queue size or buffer size, if the queue size is too large(too many items in buffer), will cause delay. For example, queue size is 2, the maximum delay is the time to process 1 data(dequeue and process), if queue size is 100, the worst condition is that delay is the time to process 99 data. So if there is something like inside wait_enqueue(), check if(q.size()==MAX_ALLOWED_SIZE, then wait, else enqueue), could be better?

**Comment by cameron314** [comment]
It sounds like you want to implement backpressure. Unfortunately, I can't justify the cost of the added semaphore overhead for every operation that would be required to make a wait_enqueue method available.

But, you could do this yourself with a simple wrapper. Something like:

    template<typename T>
    class BackpressureReaderWriterQueue {
        moodycamel::spsc_sema::LightweightSemaphore sema(128);
        moodycamel::ReaderWriterQueue<T> inner(128);

        void wait_enqueue(T&& x) {
            while (!sema.wait());
            inner.enqueue(std::move(x));  // should always succeed
        }

        bool try_dequeue(T& x) {
            if (!inner.try_dequeue(x))
                return false;
           sema.signal();
           return true;
        }
    };
