### ISSUE TITLE
Draining safely from another thread ? 

### ISSUE THREAD

**Issue by jcelerier** [cameron314/readerwriterqueue#86]
Hello,
assuming that a queue was created and is used between two threads, A (producer) & B (consumer).
If those two threads have completed execution, have been closed, etc. Is there a safe way to drain the queue from a separate thread ? 
(in order to perform an operation on elements that may have been produced but not consumed before destroying the queue).

I tried to insert a `std::atomic_thread_fence(std::memory_order_seq_cst);` before doing that operation as this seems to be what is done in the ReaderWriterQueue destructor and so far I'm not seeing issues but I'd like to know if this is just by chance or this can be safely assumed to work.

**Comment by cameron314** [comment]
If the two threads have exited, it's safe to manipulate the queue from another thread, even without the barrier. Thread creation and destruction, as well as acquiring and releasing a mutex, have specific memory ordering semantics. If I recall correctly, all effects of modifications made by one thread are guaranteed to be visible to all other threads after it has exited; certainly all effects are visible to the thread that witnesses the first thread exit (e.g. by joining it).

In general, the ownership of the readerwriterqueue can be passed between threads just like any other data structure (i.e. using the proper barriers or mutex), just with the special case that there may be separate owners for the producer and consumer halves.

**Comment by jcelerier** [comment]
> Thread creation and destruction, as well as acquiring and releasing a mutex, have specific memory ordering semantics. 

Thanks, that's what I needed to know ! Will look for an authoritative source but I'll sleep better at night.
