### ISSUE TITLE
How to trace it version data

### ISSUE THREAD

**Issue by chengm349** [cameron314/readerwriterqueue#88]
Assume I downloaded 6 months ago and now want to check whether I should download if again without go into git data to compare.

**Comment by cameron314** [comment]
Just take the master, it's been stable for a while. If you prefer, you could also take the latest "release". There were some important bugfixes for the blocking version about six months ago so I suggest you update.

**Comment by chengm349** [comment]
thanks. Hope we will hear more good news from readerwriterqueue and concurrentqueue

https://max0x7ba.github.io/atomic_queue/html/benchmarks.html

**Comment by cameron314** [comment]
Nice benchmarks!

I noticed your moodycamel ConcurrentQueue adapter doesn't use producer/consumer tokens though -- there's a good difference in performance without them.

**Comment by chengm349** [comment]
Could be for simplicity purpose. May not easy to find a suitable token (easy to maintain, understandable for code reviewer etc) for many situations. So make sense to measure its default performance (?).

**Comment by cameron314** [comment]
Tokens are pretty simple, though yes, perhaps not always applicable. But I feel without tokens it's not representing the true maximum performance that the queue can attain, which is, after all, the point of a benchmark, no?

**Comment by cameron314** [comment]
I've created a pull request that makes use of a consumer token.
