### ISSUE TITLE
`BlockingReaderWriterQueue` and `emplace`/`try_emplace` methods

### ISSUE THREAD

**Issue by sadjad** [cameron314/readerwriterqueue#92]
Hello there,

Thank you for this awesome library! Is there a reason `BlockingReaderWriterQueue` doesn't provide `emplace` and `try_emplace` methods?

https://github.com/cameron314/readerwriterqueue/blob/74a3388afea9599e07be8f3681d50cfd8870468d/readerwriterqueue.h#L745

Best,
Sadjad

**Comment by cameron314** [comment]
Just an oversight. Fixed, thanks.
