### ISSUE TITLE
can not pass cpplint 1.5.2 check

### ISSUE THREAD

**Issue by dlintw** [cameron314/readerwriterqueue#95]
Here I attached my modified version.  The major change is the deque API, it required change to pointer for output parameter to improve code readability.

[passed_cpplint152.zip](https://github.com/cameron314/readerwriterqueue/files/4901562/passed_cpplint152.zip)

**Comment by cameron314** [comment]
Sorry, not going to make this change. It rewrites most lines of code (losing blame history) for no tangible benefit.
cpplint can be configured to ignore these files.
