### ISSUE TITLE
Hitting an error during enqueue / wait_dequeue different threads

### ISSUE THREAD

**Issue by sasmaster** [cameron314/readerwriterqueue#98]
Hi, I am getting a crash here

```
		    void signal(ssize_t count = 1) AE_NO_TSAN
		    {
		    	assert(count >= 0);
		        ssize_t oldCount = m_count.fetch_add_release(count);
		        assert(oldCount >= -1);
		        if (oldCount < 0)
		        {
		            m_sema.signal(1);
		        }
		    }

```
with oldCount = -2.  Do you have an idea what could that be? I am pushing items into queue while waiting to deque from it
from another thread.

Thanks,
Michael

**Comment by cameron314** [comment]
It's as if there are two threads waiting on the queue at once.

**Comment by sasmaster** [comment]
You mean I should make sure only one thread is waiting for this queue. Single producer - consumer?

**Comment by cameron314** [comment]
Yes... this is a single-producer, single-consumer queue. If you want a MPMC queue use moodycamel::ConcurrentQueue (or Boost's, etc).

**Comment by sasmaster** [comment]
Okey, I located the issue. Indeed,I was having another thread referencing that queue and waiting on it. Many thanks for the direction and this wonderful lib  ))
